theme: jekyll-theme-minimal
title: Griffin Instruments' homepage
description: This is a placeholder for where operant box and other lab projects will be shared. Bookmark this page to keep an eye on these project updates!
